- hosts: yusrv-fr1
  tasks: 

  - name: Import password and token from pass.yml
    include_vars:
      file: pass.yml
      name: pass
    tags:
      - always

### [Drive] - Nextcloud container update

  - name: Drive | Remove Nextcloud container
    containers.podman.podman_container:
      name: Nextcloud
      state: absent
    tags:
      - drive

  - name: Drive | Remove Nextcloud image
    containers.podman.podman_image:
      name: docker.io/library/nextcloud
      state: absent
    tags:
      - drive

  - name: Drive | Recreate Nextcloud with updated image
    containers.podman.podman_container:
      image: docker.io/library/nextcloud
      pod: drive
      name: Nextcloud
      restart_policy: always
      memory: 1024m
      env:
        MYSQL_HOST: drive
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: "{{ pass['MySQL_Username'] }}"
        MYSQL_PASSWORD: "{{ pass['MySQL_Password'] }}"
        NEXTCLOUD_ADMIN_USER: "{{ pass['Nextcloud_Admin_Username'] }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ pass['Nextcloud_Admin_Password'] }}"
        NEXTCLOUD_HOSTNAME: drive 
        NEXTCLOUD_TRUSTED_DOMAINS: drive.yutetsudo.com
      volume: 
        - /home/{{ ansible_user }}/nextcloud/app:/var/www/html:Z
        - /home/{{ ansible_user }}/nextcloud/data:/var/www/html/data:Z
    tags:
      - drive

### [Music] - Navidrome container update

  - name: Music | Remove Navidrome container
    containers.podman.podman_container:
      name: Navidrome
      state: absent
    tags:
      - music

  - name: Music | Remove Navidrome image
    containers.podman.podman_image:
      name: docker.io/deluan/navidrome:latest
      state: absent
    tags:
      - music

  - name: Music | Recreate Navidrome with updated image
    containers.podman.podman_container:
      image: docker.io/deluan/navidrome:latest
      pod: music
      name: Navidrome
      restart_policy: always
      memory: 1024m
      env:
        ND_SCANSCHEDULE: 1h
        ND_LOGLEVEL: info
        ND_SESSIONTIMEOUT: 24h
        ND_MUSICFOLDER: /music
        ND_DATAFOLDER: /data
      volume: 
        - /home/{{ ansible_user }}/navidrome/music:/music:Z
        - /home/{{ ansible_user }}/navidrome/data:/data:Z
    tags:
      - music

### [Stream] - Navidrome container update

  - name: Stream | Remove Jellyfin container
    containers.podman.podman_container:
      name: jellyfin
      state: absent
    tags:
      - stream

  - name: Stream | Remove Jellyfin image
    containers.podman.podman_image:
      name: docker.io/jellyfin/jellyfin:latest
      state: absent
    tags:
      - stream

  - name: Stream | Recreate Jellyfin with updated image
    containers.podman.podman_container:
      image: docker.io/jellyfin/jellyfin:latest
      pod: stream
      name: Jellyfin
      restart_policy: always
      memory: 1024m
      volume: 
        - /home/{{ ansible_user }}/jellyfin/config:/config:Z
        - /home/{{ ansible_user }}/jellyfin/cache:/cache:Z
        - /home/{{ ansible_user }}/jellyfin/media:/media:Z
    tags:
      - stream

### [Vault] - Navidrome container update

  - name: Vault | Remove Vaultwarden container
    containers.podman.podman_container:
      name: Vaultwarden
      state: absent
    tags:
      - vault

  - name: Vault | Remove Vaultwarden image
    containers.podman.podman_image:
      name: docker.io/vaultwarden/server:latest
      state: absent
    tags:
      - vault

  - name: Vault | Recreate Vaultwarden with updated image
    containers.podman.podman_container:
      image: docker.io/vaultwarden/server:latest
      pod: vault
      name: Vaultwarden
      restart_policy: always
      memory: 512m
      env:
        ADMIN_TOKEN: "{{ pass['Vaultwarden_Token'] }}"
      volume: 
        - /home/{{ ansible_user }}/vaultwarden/data:/data:Z
    tags:
      - vault

### [Status] - Uptime Kuma container update

  - name: Status | Remove Uptime Kuma container
    containers.podman.podman_container:
      name: Uptime-Kuma
      state: absent
    tags:
      - status

  - name: Status | Remove Uptime Kuma image
    containers.podman.podman_image:
      name: docker.io/louislam/uptime-kuma:latest
      state: absent
    tags:
      - status

  - name: Status | Recreate Uptime Kuma with updated image
    containers.podman.podman_container:
      image: docker.io/louislam/uptime-kuma:latest
      pod: status
      name: Uptime-Kuma
      restart_policy: always
      memory: 512m
      volume: 
        - /home/{{ ansible_user }}/kuma/data:/app/data:Z
    tags:
      - status
